=== alexsocias/Lenguajedemarcas/actividad11/tabla.dtd
<!ELEMENT acon (evento+)>
<!ELEMENT evento (fecha)>
<!ATTLIST evento nombre CDATA #REQUIRED>
<!ELEMENT fecha (dia,mes,año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== alexsocias/Lenguajedemarcas/actividad11/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE acon SYSTEM "tabla.dtd">
<acon>
    <evento nombre="IMB da a conocer el PC">
        <fecha>
            <dia>12</dia>
            <mes>8</mes>
            <año>1981</año>
        </fecha>
    </evento> 
    <evento nombre="Se funda Google">
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <año>1998</año> 
        </fecha>
    </evento>
    <evento nombre="Se funda facebook">
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <año>2004</año> 
        </fecha>
    </evento>
</acon>
